name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *' # every day at 2:00 AM
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          owner: coolsnowwolf
          repo: lede
          base: master
          head: master
